development:
    clients:
        default:
            database: blog_development
            hosts:
                - localhost:27017
            options:
                server_selection_timeout: 1
# development:
#   clients:
#     default:
#       uri: mongodb+srv://user:pass@yourcluster.mongodb.net/blog_development?retryWrites=true&w=majority
#       options:
#         server_selection_timeout: 5
